- name: Altera hostname
  ansible.builtin.hostname:
    name: "{{ novo_hostname }}"
    use: systemd

- name: Cria novo usuário do cofre de senhas YDUQS
  ansible.builtin.user:
    name: '{{ usuario_cofre }}'
    comment: "Usuário do cofre"
    password: '{{ password_usuario_cofre }}'
    shell: /bin/bash
    state: present

- name: Adiciona usuario do cofre no sudo
  lineinfile:
    path: /etc/sudoers.d/{{ usuario_cofre }}
    line: '{{ usuario_cofre }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

- name: Valida includedir no /etc/sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: Checa se o usuario do cofre existe
  command: grep -P '^[ \t]*AllowUsers[ \t]+([-\w ]+[ \t]+)*{{ usuario_cofre }}([ \t]+.+)*$' /etc/ssh/sshd_config
  register: allow_users_exists
  changed_when: no
  ignore_errors: yes

- name: Adiciona usuário do cofre no AllowUsers
  lineinfile:
    regexp: '^[ \t]*AllowUsers([ \t]+.*)$'
    line: 'AllowUsers {{ usuario_cofre }}\g<1>'
    dest: /etc/ssh/sshd_config
    backrefs: yes
    validate: sshd -t -f %s
  when: allow_users_exists.rc != 0
  notify:
    - reload sshd

- name: Atualiza objetivo do arquivo server-comments
  lineinfile:
    path: /etc/server-comments
    regexp: "^objetivo - .*"
    line: "{{ novo_hostname }} - {{ objetivo }}"

- name: Atualiza responsaveis do arquivo server-comments
  lineinfile:
    path: /etc/server-comments
    line: "Responsaveis: {{ responsaveis }}"
    insertafter: "^objetivo - .*"

- name: Configura novo IP de producao na interface ens192
  community.general.nmcli:
    conn_name: ens192
    ifname: ens192
    type: ethernet
    ip4: "{{ ip_producao }}"
    gw4: "{{ ip_gateway_producao }}"
    state: present

- name: Configura novo IP de gerencia na interface ens224
  community.general.nmcli:
    conn_name: ens224
    ifname: ens224
    type: ethernet
    ip4: "{{ ip_gerencia }}"
    state: present

- name: Adiciona rota 01
  shell: |
    nmcli connection modify ens224 +ipv4.routes "{{ ip_route_gerencia01 }} {{ ip_gateway_gerencia }}"
    ip route add "{{ ip_route_gerencia01 }}" via "{{ ip_gateway_gerencia }}" dev ens224

- name: Adiciona rota 02
  shell: |
    nmcli connection modify ens224 +ipv4.routes "{{ ip_route_gerencia02 }} {{ ip_gateway_gerencia }}"
    ip route add "{{ ip_route_gerencia02 }}" via "{{ ip_gateway_gerencia }}" dev ens224

- name: Adiciona rota 03
  shell: |
    nmcli connection modify ens224 +ipv4.routes "{{ ip_route_gerencia03 }} {{ ip_gateway_gerencia }}"
    ip route add "{{ ip_route_gerencia03 }}" via "{{ ip_gateway_gerencia }}" dev ens224

- name: Registra no subscription da Red Hat
  when: ansible_distribution == 'RedHat'
  community.general.redhat_subscription:
    state: present
    username: "{{ username_rhel_subscription }}"
    password: "{{ password_rhel_subscription }}"
    pool_ids: "{{ pool_id_rhel_subscription }}"

- name: Desativa SELinux
  selinux:
    state: disabled

- name: Upgrade de todos os pacotes do SO
  yum:
    name: '*'
    state: latest

- name: Instala pacote net-tools e mokutil
  yum:
    name: 
      - net-tools
      - mokutil
    state: latest

- name: Verifica a versão do sistema operacional
  command: "{{ item }}"
  loop:
    - "cat /etc/redhat-release"
    - "cat /etc/oracle-release"
  register: release_output
  changed_when: false

- name: Instala repositorio zabbix el9
  when: "'9' in release_output.results[0].stdout or '9' in release_output.results[1].stdout"
  command: "rpm -Uvh https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm"

- name: Instala repositorio zabbix el8
  when: "'8' in release_output.results[0].stdout or '8' in release_output.results[1].stdout"
  command: "rpm -Uvh https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm"

- name: Cria diretório /etc/zabbix, caso nao exista
  file:
    path: /etc/zabbix
    state: directory
    mode: 0755
    recurse: yes
    force: yes

- name: Instalar o pacote zabbix_agent
  yum:
    name: zabbix-agent
    state: latest

- name: Atualiza arquivo de configuracao do agente do Zabbix
  copy:
    src: conf/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    force: yes
  notify:
    - Start Zabbix-agent
      
- name: Copia arquivo ISO do agente do HPOM
  copy:
    src: "files/{{ hpom_installer }}"
    dest: "/home/ansible"

- name: Copia arquivos adicionais para o HPOM para versao do SO 9
  when: "'9' in release_output.results[0].stdout or '9' in release_output.results[1].stdout"
  copy:
    src: "files/ncurses-compat-libs-6.2-8.20210508.el9.x86_64.rpm"
    dest: "/home/ansible"

- name: Instala pacotes adicionais para o HPOM para versao do SO 9
  when: "'9' in release_output.results[0].stdout or '9' in release_output.results[1].stdout"
  command: "rpm -Uvh /home/ansible/ncurses-compat-libs-6.2-8.20210508.el9.x86_64.rpm"

- name: Copia arquivo script de instalação do monitoramento Cirion
  copy:
    src: "files/{{ hpom_installer_script }}"
    dest: "/home/ansible"

- name: Torna script_hpmon.sh executável
  file:
    path: "/home/ansible/{{ hpom_installer_script }}"
    mode: 0755

- name: Instala e configurando o monitoramento da Cirion
  shell: "/home/ansible/{{ hpom_installer_script }}"

- name: Configura Hosts da nova VM
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ item }}"
  with_items:
    - ""
    - "#### RESOLVE PROBLEMA DE RESOLUÇÃO DE NOME COM O DNS #######"
    - "{{ ip_producao }} {{ novo_hostname }}.estacio.corp {{ novo_hostname }}"
    - "{{ ip_gerencia }} {{ novo_hostname }}"

- name: Remove os arquivos copiados para /home/ansible
  command: "rm -rf /home/ansible/*.rpm"

