---
- name: restart sshd
  systemd:
    state: restarted
    daemon_reload: yes
    name: sshd

- name: Restart network
  systemd:
    name: NetworkManager
    state: restarted

- name: Start zabbix-agent
  systemd: 
    name: zabbix-agent
    state: restarted
    enabled: yes
...

